### ISSUE TITLE
beers_dirty_5_explicitmissingvalue: Attribute tid is replaced by null

### ISSUE THREAD

**Issue by visenger** [BigDaMa/error-generator#4]
By grouping the generated data
 dirtyData.groupBy(col("tid")).count().where(col("count") > 11) results in
+----+-----+
| tid|count|
+----+-----+
|null|   77|
+----+-----+

The "tid" attribute is null. The tid attribute was inserted by us and shouldn't participate in the process of error injection.

**Comment by Milad-abbaszadeh** [comment]
we consider all columns in the dataset, as columns that the error generator can violate them.because in the real word id column also can have the error.
 
for solving the problem there are two options
1)add the "td" after the violation step to make sure that would remain the same.
2) add another feature to our tool that user can say I don't need errors in this particular columns.

what's your idea?

**Comment by FelixNeutatz** [comment]
I would add the feature that the user can choose which attributes can be changed and which not.
